"""
pylunasvg is python bindings for lunasvg library
"""
from __future__ import annotations
import typing
import typing_extensions
__all__: list[str] = ['Bitmap', 'Box', 'Document', 'Element', 'Matrix', 'Node', 'TextNode', 'lunasvg_add_font_face_from_data', 'lunasvg_add_font_face_from_file', 'lunasvg_version', 'lunasvg_version_string']

class Bitmap:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, data: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, bitmap: Bitmap) -> None:
        ...
    def assign(self, arg0: Bitmap) -> Bitmap:
        ...
    def clear(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def convertToRGBA(self) -> None:
        ...
    def data(self) -> int:
        ...
    def height(self) -> int:
        ...
    def isNull(self) -> bool:
        ...
    def stride(self) -> int:
        ...
    def swap(self, arg0: Bitmap) -> None:
        ...
    def valid(self) -> bool:
        ...
    def width(self) -> int:
        ...
    @typing.overload
    def writeToPng(self, filename: str) -> bool:
        ...
    @typing.overload
    def writeToPng(self, callback: ..., closure: typing_extensions.CapsuleType) -> bool:
        ...
class Box:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, x: typing.SupportsFloat | typing.SupportsIndex, y: typing.SupportsFloat | typing.SupportsIndex, w: typing.SupportsFloat | typing.SupportsIndex, h: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def transform(self, matrix: ...) -> Box:
        ...
    def transformed(self, matrix: ...) -> Box:
        ...
    @property
    def h(self) -> float:
        ...
    @h.setter
    def h(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def w(self) -> float:
        ...
    @w.setter
    def w(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Document:
    @staticmethod
    @typing.overload
    def loadFromData(string: str) -> Document:
        ...
    @staticmethod
    @typing.overload
    def loadFromData(data: str, size: typing.SupportsInt | typing.SupportsIndex) -> Document:
        ...
    @staticmethod
    def loadFromFile(filename: str) -> Document:
        ...
    def applyStyleSheet(self, content: str) -> None:
        ...
    def boundingBox(self) -> Box:
        ...
    def documentElement(self) -> Element:
        ...
    def elementFromPoint(self, x: typing.SupportsFloat | typing.SupportsIndex, y: typing.SupportsFloat | typing.SupportsIndex) -> Element:
        ...
    def forceLayout(self) -> None:
        ...
    def getElementById(self, id: str) -> Element:
        ...
    def height(self) -> float:
        ...
    def querySelectorAll(self, content: str) -> list[Element]:
        ...
    def render(self, bitmap: Bitmap, matrix: Matrix = ...) -> None:
        ...
    def renderToBitmap(self, width: typing.SupportsInt | typing.SupportsIndex = -1, height: typing.SupportsInt | typing.SupportsIndex = -1, backgroundColor: typing.SupportsInt | typing.SupportsIndex = 0) -> Bitmap:
        ...
    def updateLayout(self) -> None:
        ...
    def width(self) -> float:
        ...
class Element(Node):
    def __init__(self) -> None:
        ...
    def children(self) -> list[Node]:
        ...
    def getAttribute(self, name: str) -> str:
        ...
    def getBoundingBox(self) -> Box:
        ...
    def getGlobalBoundingBox(self) -> Box:
        ...
    def getGlobalMatrix(self) -> Matrix:
        ...
    def getLocalBoundingBox(self) -> Box:
        ...
    def getLocalMatrix(self) -> Matrix:
        ...
    def hasAttribute(self, name: str) -> bool:
        ...
    def render(self, bitmap: Bitmap, matrix: Matrix = ...) -> None:
        ...
    def renderToBitmap(self, width: typing.SupportsInt | typing.SupportsIndex = -1, height: typing.SupportsInt | typing.SupportsIndex = -1, backgroundColor: typing.SupportsInt | typing.SupportsIndex = 0) -> Bitmap:
        ...
    def setAttribute(self, name: str, value: str) -> None:
        ...
class Matrix:
    @staticmethod
    def rotated(angle: typing.SupportsFloat | typing.SupportsIndex, cx: typing.SupportsFloat | typing.SupportsIndex = 0.0, cy: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> Matrix:
        ...
    @staticmethod
    def scaled(sx: typing.SupportsFloat | typing.SupportsIndex, sy: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @staticmethod
    def sheared(shx: typing.SupportsFloat | typing.SupportsIndex, shy: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @staticmethod
    def translated(tx: typing.SupportsFloat | typing.SupportsIndex, ty: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __imul__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, c: typing.SupportsFloat | typing.SupportsIndex, d: typing.SupportsFloat | typing.SupportsIndex, e: typing.SupportsFloat | typing.SupportsIndex, f: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __mul__(self, arg0: Matrix) -> Matrix:
        ...
    def inverse(self) -> Matrix:
        ...
    def invert(self) -> Matrix:
        ...
    def multiply(self, arg0: Matrix) -> Matrix:
        ...
    def reset(self) -> None:
        ...
    def rotate(self, angle: typing.SupportsFloat | typing.SupportsIndex, cx: typing.SupportsFloat | typing.SupportsIndex = 0.0, cy: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> Matrix:
        ...
    def scale(self, sx: typing.SupportsFloat | typing.SupportsIndex, sy: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def shear(self, shx: typing.SupportsFloat | typing.SupportsIndex, shy: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def translate(self, tx: typing.SupportsFloat | typing.SupportsIndex, ty: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @property
    def a(self) -> float:
        ...
    @a.setter
    def a(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def b(self) -> float:
        ...
    @b.setter
    def b(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def c(self) -> float:
        ...
    @c.setter
    def c(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def d(self) -> float:
        ...
    @d.setter
    def d(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def e(self) -> float:
        ...
    @e.setter
    def e(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def f(self) -> float:
        ...
    @f.setter
    def f(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Node:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, node: Node) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, node: Node) -> bool:
        ...
    def isElement(self) -> bool:
        ...
    def isNull(self) -> bool:
        ...
    def isTextNode(self) -> bool:
        ...
    def parentElement(self) -> ...:
        ...
    def toElement(self) -> ...:
        ...
    def toTextNode(self) -> ...:
        ...
class TextNode(Node):
    def __init__(self) -> None:
        ...
    def data(self) -> str:
        ...
    def setData(self, data: str) -> None:
        ...
def lunasvg_add_font_face_from_data(family: str, bold: bool, italic: bool, data: bytes) -> bool:
    ...
def lunasvg_add_font_face_from_file(arg0: str, arg1: bool, arg2: bool, arg3: str) -> bool:
    ...
def lunasvg_version() -> int:
    ...
def lunasvg_version_string() -> str:
    ...
